import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const sourGummy = localFont({
  src: "./fonts/SourGummyVF.ttf",
  variable: "--font-sour-gummy",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/sign-in">
      <html lang="en">
        <body
          className={`${sourGummy.variable} antialiased`}
        >
          <div className='w-full h-screen px-0 md:px-5 flex justify-center items-center bg-gradient-to-r from-custom-400 via-custom-500 to-custom-600'>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
